### ISSUE TITLE
Added support WINBOND W25Q16CV

### ISSUE THREAD

**Issue by GermanAizek** [bigbigmdm/IMSProg#108]
### Description

@bigbigmdm,
Datasheet: https://www.alldatasheet.com/datasheet-pdf/pdf/555256/WINBOND/W25Q16CVSSIG.html

### Usage tips

There is already a similar chip, just edit it and added new.

![image](https://github.com/user-attachments/assets/ac681ed4-3ae3-47e0-81ff-c131250683b5)

**Comment by bigbigmdm** [comment]
@GermanAizek , these chips have the same JEDEC ID - EF/40/16. They have the same read, erase, write operations for the programmer. Since IMSProg determines the chip by the JEDEC ID value, I do not add chips with the same JEDEC ID to the database on purpose. Otherwise the program will take data from the database of the first chip with such JEDEC ID value.
